title: Ridho Ryan Ghifari
email: ridhoryanghifari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog by Ridho Ryan Ghifari. I am a student at Politeknik Negeri Lhokseumawe, 
  and I was born on October 23, 2005. This blog is built using Jekyll and hosted on GitHub Pages. 
  The content is primarily in Indonesian, but some posts are written in English.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://ridhoryanghifari.github.io" # the base hostname & protocol for your site

github_username: ridhoryanghifari

collections:
  students:
    output: true
    permalink: /students/:name/
    title: Students
